version: "3.9"

services:
  web:
    volumes: 
      - web-files:/usr/src/web

    build: web
    command: tail -f /dev/null

  app:
    ports: 
      - "5000:5000"
    volumes: 
      - web-files:/usr/src/app/web
    build: app

volumes:
  #volume to combine app and web files/folders.
  web-files: