version: "3.9"

services:
  app:
    build:
        context: .
        dockerfile: app/Dockerfile
    ports: 
      - "5000:5000"
    command: tail -f
    volumes: 
      - ./requirements:/usr/src/requirements
      # - web:/usr/src/web
      # - requirements:/usr/src/requirements
      # - app:/usr/src/app
      