version: "3.9"

services:
  web:
    build: web
    ports: 
      - "80:80"
    volumes: 
      - all-files:/usr/src/web

    command: tail -f /dev/null

  app:
    ports: 
      - "5000:5000"
    volumes: 
      - all-files:/usr/src/app
    build: app

volumes:
  #volume to combine app and web files/folders.
  all-files: