version: "3.9"

services:
  main-program:
    container_name: python-development
    image: hellojenkins-local-dev:latest
    ports: 
      - "5000:5000"
    volumes: 
      - ./app/:/usr/src/app/

    command: python /usr/src/app/driver.py
    