version: "3.9"
# This composed file is used to run Python tests

services:
  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: pytest test_basic.py
      # volumes: 
      #   - app-files:/usr/src/app

  # app:
  # build: app
  # volumes:
  #   - /requirements/requirements.txt:/usr/src/app/
  #   # - app-files:/usr/src/app/
  #   # Overriding default command and doing nothing as I only need the app folder files.
  #   command: "false"

volumes:
  #volume to combine app and test files/folders.
  app-files: