version: "3.9"

services:
  app:
    build: app
    volumes: 
      - app-files:/usr/src/app/
      # Overriding default command and doing nothing as I only need the app folder files.
      command: 

  tests:
    build: tests
    volumes: 
      - app-files:/usr/src/app

volumes:
  #volume to combine app and test files/folders.
  app-files