version: "3.9"

services:
  web:
    build: web

  app:
    container_name: python-development
    image: hellojenkins-local-dev:latest
    ports: 
      - "5000:5000"

    command: python /usr/src/app/driver.py
    