version: "3.9"

services:
  app:
    build:
        context: .
        dockerfile: app/Dockerfile
    ports: 
      - "5000:5000"
    volumes: 
      - ./web:/usr/src/app/web
      - ./requirements:/usr/src/requirements
      - ./app:/usr/src/app
    command: tail -f