version: "3.9"

services:
  web:
    build: web
    ports: 
      - "80:80"
    volumes: 
      - all-files:/usr/src/web/

  app:
    build: app
    container_name: python-development
    ports: 
      - "5000:5000"
    volumes: 
      - all-files:/usr/src/app

volumes:
  - all-files: #volume to combine app and web files/folders.