version: "3.9"
# This composed file is used to run Python tests

services:
  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile

    volumes: 
    - ./tests:/usr/src/tests
    - ./app:/usr/src/app

    command: tail -f
    # command: pytest test_driver.py
